---
title: "boxplots of biosynthesis samples 09102025"
output: html_document
date: "2025-08-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Marquis.Yazzie/OneDrive - University of Denver/Desktop/DU Research/10012025_Alexa_Batch_metallophore_quant/box_plots")
```

```{r}
library(ggplot2)
library(stringr)
library(data.table)
library(readr)
library(dplyr)
library(tidyr)
library(reshape)     
library(gplots)
library(pheatmap)
library(heatmap3)
library(magrittr) 
library(tibble) 
library(RColorBrewer)
library(paletteer)
library(clr)
library(tidyverse) #used for data science. The eight core packages inside this library are: ggplot2 (data visualisation), dplyr (data manipulation), tidyr, readr, purrr, tibble, stringr, and forcats
library(KODAMA) # to use the normalisation function
library(ggrepel) #mainly used to repel overlapping text labels in ggplots
library(vegan) #popular library for analysing ecological diversity and for multivariate analysis of community data. Here, we use it for PCoA
library(svglite) #to save the plots in support vector graphics (svg) format
library(factoextra) #for extracting and visualizing outputs of multivariate analyses such as PCA, k-means
library(ggsci) #provides color palettes for ggplot2 that can be used for scientific journals
library(matrixStats) #contains highly optimized functions to perform statistics on matrix data
library(cowplot) #efficient functions to arrange several plots
library(ggpubr)
```


```{r}
ft <- read.csv("05262026_RT_window_0point15_FMHW_0point1_iimn_gnps_quant.csv", header = T, check.names = F)
md <- read.csv("metadata.csv", header = T, check.names = F)
```

```{r}
quant <- t(ft)
quant <- as.data.frame(quant)

new_colnames <- as.character(quant[1, ])
quant <- quant[-1,]

colnames(quant) <- new_colnames

quant <- quant[grep(".mzML", rownames(quant)), ]


```

```{r}
numeric_columns <- sapply(quant, is.numeric)
numeric_columns

convert_to_numeric <- function(column) {
  as.numeric(as.character(column))
}

# Apply the function to all columns
quant <- quant %>% mutate_all(convert_to_numeric)
```


```{r}
quant <- quant %>% tibble::rownames_to_column("filename")


quant <- md %>% dplyr::select("filename", "Alternate_name") %>% 
  left_join(quant, by = "filename")

quant <- md %>% dplyr::select("filename", "Nd_type") %>% 
  left_join(quant, by = "filename")

#quant <- md %>% dplyr::select("filename", "Acquisition_order") %>% 
 # left_join(quant, by = "filename")

quant_blank <- quant %>%
  filter(Alternate_name %in% c("Method_blk", "Ext_blk", "Media_blk"))

quant<- subset(quant, Alternate_name != "Ext_blk")

quant<- subset(quant, Alternate_name  != "Method_blk")

quant<- subset(quant, Alternate_name != "Media_blk")

quant<- subset(quant, Alternate_name != "_-mllF/+PA1_AsbF")

quant<- subset(quant, Alternate_name != "_-AsbF_like_2877")

quant<- subset(quant, Alternate_name != "_-mllJ")


```

```{r}
quant$Alternate_name <- factor(
  quant$Alternate_name,
  levels = c("_-mllF", "_-mllF/+PA1_AsbF_IPTG", "_-mllG", "_-mllG/-AsbF_like_2877")
)
```


```{r}
y_columns <- c(" 6141", " 3587", " 4596" , " 4145", " 4371")
```

```{r}
plot_list <- lapply(y_columns, function(y_var) {
  
  ggplot(quant, aes(Alternate_name, y = .data[[y_var]], shape = Nd_type)) +
     geom_boxplot(
      aes(fill = Nd_type),
      outlier.shape = NA,
      width = 0.6
    ) +

    geom_jitter(
      aes(color = Nd_type, shape = Nd_type),
      width = 0.15,
      size = 3,
      alpha = 0.8
    )  +
  theme_classic() + 
    labs(y = paste("Peak area (AU) -", y_var), x = "", shape = "") +
    theme(
      axis.title.x = element_text(family = "sans", size = 16, hjust = 0.5),  
      axis.title.y = element_text(family = "sans", size = 16, hjust = 0.5),  
      axis.text.x = element_text(family = "sans", size = 16, color = "black", angle = 45, hjust = 1), 
      axis.text.y = element_text(family = "sans", size = 16, color = "black"),
      axis.line = element_line(size = 1),
      axis.ticks = element_line(size = 1), 
      axis.ticks.length = unit(.25, "cm"),
      legend.text = element_text(size = 14, family = "sans")
    )   
})

# Save each plot with a unique filename
for (i in seq_along(plot_list)) {
  ggsave(
    filename = paste0("plot_", y_columns[i], ".png"), # name by column
    plot     = plot_list[[i]],
    width    = 8,
    height   = 6,
    dpi      = 300
  )
}

# Print all plots
plot_list


```

```{r}
quant_MLL_rh <- quant %>%
  dplyr::select(
    1:3,
    ` 4596`,
    ` 4145`
  )

quant_long <- quant_MLL_rh %>%
  pivot_longer(
    cols = c(` 4596`, ` 4145`),   # ONLY the two features
    names_to = "Feature",
    values_to = "PeakArea"
  )
```

```{r}
quant_long$Alternate_name <- factor(
  quant_long$Alternate_name,
  levels = c("_-mllF", "_-mllF/+PA1_AsbF_IPTG", "_-mllG", "_-mllG/-AsbF_like_2877")
)
```

```{r}

quant_long <- quant_long %>%
  dplyr::filter(!(Alternate_name == "_-mllG" & Nd_type == "CL"))
```


```{r}
boxplot_MLL_rh <- ggplot(quant_long,
       aes(x = Alternate_name,
           y = PeakArea,
           fill = Feature)) +

  geom_boxplot(
    position = position_dodge(width = 0.8),
    outlier.shape = NA,
    width = 0.7
  ) +

  geom_jitter(
    aes(color = Feature),
    position = position_jitterdodge(
      jitter.width = 0.15,
      dodge.width = 0.8
    ),
    size = 3,
    alpha = 0.8
  ) +

  scale_fill_manual(values = c(
    " 4596" = "#F8766D",
    " 4145" = "#00BFC4"
  )) +

  scale_color_manual(values = c(
    " 4596" = "#F8766D",
    " 4145" = "#00BFC4"
  )) +

  theme_classic() +

  labs(
    x = "",
    y = "Peak area (AU)",
    fill = "Feature",
    color = "Feature"
  ) +

  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    axis.text.x = element_text(size = 16, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 16),
    legend.text = element_text(size = 14)
  )



ggsave(
  filename = "boxplot_MLL_rh.svg",
  plot = boxplot_MLL_rh,
  width = 6,
  height = 5
)
```






```{r}
plot_list <- lapply(y_columns, function(y_var) {
  
  ggplot(quant_blank, aes(Alternate_name, y = .data[[y_var]])) +
    geom_point(size = 3) +
  theme_classic() + 
    labs(y = paste("Peak area (AU) -", y_var), x = "", shape = "") +
    theme(
      axis.title.x = element_text(family = "sans", size = 16, hjust = 0.5),  
      axis.title.y = element_text(family = "sans", size = 16, hjust = 0.5),  
      axis.text.x = element_text(family = "sans", size = 16, color = "black", angle = 45, hjust = 1), 
      axis.text.y = element_text(family = "sans", size = 16, color = "black"),
      axis.line = element_line(size = 1),
      axis.ticks = element_line(size = 1), 
      axis.ticks.length = unit(.25, "cm"),
      legend.text = element_text(size = 14, family = "sans")
    )   
})

# Save each plot with a unique filename
for (i in seq_along(plot_list)) {
  ggsave(
    filename = paste0("blank_only_", y_columns[i], ".png"), # name by column
    plot     = plot_list[[i]],
    width    = 8,
    height   = 6,
    dpi      = 300
  )
}

# Print all plots
plot_list
```



```{r}
cleaned_df <- quant %>%
  select(1:3, ` 4596`, ` 4145`)
```

```{r}
write.csv(cleaned_df, "cleaned_df.csv", row.names=FALSE)
```

